### ISSUE TITLE
UI redesign

### ISSUE THREAD

**Issue by LodedWimp** [J6co0b/jmenu#8]
(IDC about this, just asking for other people)
The UI seems really messy, and is it possible to hide the end, as maybe there’s people who might have to hide the menu, in case your nearby teacher or family member notices?

**Comment by broQUAZK** [comment]
I agree the owner should make it look better instead of it being messy

**Comment by J6co0b** [comment]
I am currently working on intervoid which will have a much smoother design than jmenu. Jmenu is way to big and its not formatted as well.
